body:
  - type: textarea
    id: tmate
    attributes:
      label: "[Optional] How do you use tmate-ssh-server?"
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: "[Optional] Can you provide us with a quote on your favourite part of tmate-ssh-server? This may be used in marketing material."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "[Optional] What type of events are you monitoring (see https://khulnasoft-lab.github.io/tmate-ssh-server/latest/docs/events/)?"
      options:
        - label: "security"
        - label: "network"
        - label: "lsm"
        - label: "containers"
        - label: "misc"
        - label: "syscalls"
        - label: "custom"
  - type: markdown
    attributes:
      value: |
        ## Get in touch
        We are always looking for 
        * User feedback
        * Collaboration with other companies and organisations
        * Or just to have a chat with you about tmate-ssh-server. 
        If any of this interests you or your marketing team, please reach out at: oss@khulnasoft.com
        We would love to hear from you!
